services:
  - type: web
    name: ara-voice
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: APPS_SCRIPT_URL
        sync: false  # Set this manually in Render dashboard